citizenos/citizenos-api

models/Moderator.js
routes/api/topic.js
test/api/topic.js
test/libs/models/Moderator.js

Add global moderator functionality

Global moderator

---

CHANGELOG.md
libs/passport/index.js
npm-shrinkwrap.json
package.json

Update google login to avoid getting caught by Google+ deprecation

updated passport google oauth https://github.com/citizenos/citizenos-api/issues/72

---

routes/api/activity.js

Fix for https://github.com/citizenos/citizenos-api/issues/64

activity feed, fix duplicate activities

---

CHANGELOG.md
routes/api/user.js
test/api/user.js

https://github.com/citizenos/citizenos-api/issues/54

Make users verify updated email address

---

.github/ISSUE_TEMPLATE/bug_report.md

Created a template to submit bug reports, in order to simplify receiving unified bug reports with required information.

New issue template (BUG:)

---

routes/api/discussion.js
routes/api/topic.js

Fixed a bug, so that user will be added as  members of the topic when they post arguments. Also users will be added as members when turning on notifications for the topic

Add user as topic member user when turning on topic notifications

---

routes/api/ideation.js

Steps to test:
- Join idea gathering with user that has less than admin privileges
- post and idea
- try to edit this idea
Current: 
- Error insufficient permissions message
Expected:
- Edit should be successful

FIX https://github.com/citizenos/citizenos-fe/issues/1361

---

routes/api/discussion.js
routes/api/ideation.js
routes/api/topic.js

Refactor adding user as member into a function, added it also into idea votes endpoint, idea comments endpoint and discussion argument vote endpoint

Add user as member when votingon ideas and arguments

---

routes/api/group.js
routes/api/topic.js
test/api/group.js

Remove users phone and email info from admin info

FIX FE#1839

---

routes/api/group.js
routes/api/topic.js

In order to proceed with new design we need to extend invitations api with some additional fields

Feature: Add additional fields for topic/group invitations [#1386]

---

db/migrations/20250210180745-alter-ideation-add-template.js
db/models/Ideation.js
routes/api/ideation.js
test/api/ideation.js

In order to implement idea template feature, we need to add template column to ideation table:
https://github.com/citizenos/citizenos-fe/issues/1822

Feature: Add template column to ideation table [#1822]

---

db/migrations/20250210180745-alter-ideation-add-template.js
db/models/Ideation.js
routes/api/ideation.js
test/api/ideation.js

In order to implement idea template feature, we need to add template column to ideation table:
https://github.com/citizenos/citizenos-fe/issues/1822

Feature: Add idea template field to idea table [#1822]

---

libs/util.js
routes/api/ideation.js

Steps to test:
- export anonymous ideas to csv
Current:
- empty file
Expected:
- exported ideas to csv
- add additional columns (age, gender, residence)

Feature: Add demographics fields to csv export [#1865]

---

routes/api/ideation.js

Fix: Decogrophics config on ideation create [#1865]

---

routes/api/ideation.js

Steps to test:
- update idea question
Current:
- question is not updated
Expected:
- question is updated

Fix: Edited question not saved [#2002]

---

routes/api/ideation.js

Fix ideas counter as per requirements: https://github.com/citizenos/citizenos-fe/issues/2043#issuecomment-2711135696 (first bullet point)

Fix: Exclude draft ideas from counter [#2043]

---

routes/api/ideation.js

Update csv as per requirements: https://github.com/citizenos/citizenos-fe/issues/2043#issuecomment-2711135696

Chore: Exclude draft from csv [#2043]

---

routes/api/auth.js

`setAuthCookie` after user followed verification link.
> Note: we do it once when `emailIsVerified` is false

Chore: Auth user after verification email [#2084]

---

routes/api/user.js

Fix for https://github.com/citizenos/citizenos-fe/issues/2098

Chore: Add redirectSuccess to update user method [#2098]

---

db/migrations/20250319122353-alter-reports-update-type.js

Fix for https://github.com/citizenos/citizenos-fe/issues/2086
> Note: Made rollback as for other similar migrations

Fix: 500 error when reporting ideas ('Other' option) [#2086]

---

routes/api/ideation.js

https://github.com/citizenos/citizenos-fe/issues/2138

Fix: Filter by participant showing names of participants [#2138]

---

routes/api/activity.js

https://github.com/citizenos/citizenos-fe/issues/2139

Chore: Filter out draft activities [#2139]

---

.gitignore
CHANGELOG.md
Dockerfile
docker-compose.yml
eslint.config.mjs
npm-shrinkwrap.json
package.json
routes/api/activity.js
routes/api/ideation.js

https://github.com/citizenos/citizenos-fe/issues/1528

Feature: Add search function to ideas [#1528]
